### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
@swapnilsparsh I have created Pagination in that 30 project in one page

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-26 02-46-19

**Comment by Bharadwajshivam28** [comment]
A simple box

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 You dont have to make different files for pagination. make changes in index.html file only and its respective CSS and JS file. Also make a new branch and open a fresh PR as your previous PR commits are getting mentioned here so I am closing this PR

**Comment by Bharadwajshivam28** [comment]
ok sir

**Pull request closed without merging**
