### PR TITLE
Issue #140 News Website

### PR DESCRIPTION
**Pull request by Jyo561**
Used VanilaJS,Bulma and NewsData API

Its request to added this PR under GSSoC22 as it is contributed under it

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great Project
Update the project number as project number 54 has already been added to the repo.

**Comment by Jyo561** [comment]
Please add it now because i had to change the directory twice because of adding of other projects

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great Project
Update the project number as project number 55 has already been added to the repo.

**Comment by Jyo561** [comment]
I have done it to 56

**Comment by Jyo561** [comment]
Please check and add it

**Comment by Jyo561** [comment]
Please add it i had changed the directory name twice as you said please add it or else i will have to change it again

**Comment by Jyo561** [comment]
Sir please add this PR please

**Pull request closed without merging**
