### PR TITLE
Simple Library Management

### PR DESCRIPTION
**Pull request by samipak458**
### Issue no.: #465

A simple Library Management Project which is easy to use and understand as a beginner.
This Project is very helpful in understanding the concept of Local Storage and search the book by name of book, author and type. I make this project with the help of HTML, CSS, Bootstrap & JavaScript.

image

### CODE REVIEW

**Comment by samipak458** [comment]
@swapnilsparsh kindly review my PR.

**Comment by samipak458** [comment]
@swapnilsparsh kindly review and merge my PR.

**Comment by swapnilsparsh** [comment]
@samipak458 Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Comment by samipak458** [comment]
Welcome! I will surely contribute more  🥂

> @samipak458 Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Pull request merged**
