### PR TITLE
Created a New Landing Page 

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Created New Page with hover effect , perfect color combination and  customized proper adjustment of projects 

@swapnilsparsh

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
if more changes then please comment sir @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 
Keep the following points in mind while making the new layout:

1. Use this Color Pallete
#1A1423 - Raisin Black
#3D314A - English Violet
#684756 - Eggplant

2. Background should be plain/gradient with good color combination and no photo
3. One single font will be used in whole page 
4. You dont have to remove the functionality which were therer in previous landing page like the night mode and the github logo on the top right corner which take you to the repo.
5. Put 4 projects in one row.

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-07 18-59-42

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Is it looking correct sir or if any changes needed ?

**Comment by Bharadwajshivam28** [comment]
It has hover effect also but it is not in picture @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
[Screencast from 02-07-2023 07:12:52 PM.webm](https://user-images.githubusercontent.com/108119109/217261491-9995d957-ec97-450c-a332-e18ea7276a88.webm)

**Comment by Bharadwajshivam28** [comment]
See the hover effect @swapnilsparsh

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh Is it looking correct sir or if any changes needed ?

Why didn't you use the color which I have mentioned above ?
Use the colors which I have mentioned above or make a new gradient.
The color gradient is looking very contrast, go to [this site](https://coolors.co/gradient-maker/a4c6b8-5e435d)

**Comment by Bharadwajshivam28** [comment]
> > @swapnilsparsh Is it looking correct sir or if any changes needed ?
> 
> Why didn't you use the color which I have mentioned above ?
> Use the colors which I have mentioned above or make a new gradient.
> The color gradient is looking very contrast, go to [this site](https://coolors.co/gradient-maker/a4c6b8-5e435d) 

Ok sir @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
> > @swapnilsparsh Is it looking correct sir or if any changes needed ?
> 
> Why didn't you use the color which I have mentioned above ?
> Use the colors which I have mentioned above or make a new gradient.
> The color gradient is looking very contrast, go to [this site](https://coolors.co/gradient-maker/a4c6b8-5e435d) 

Wll correct it sir @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-08 12-50-19

**Comment by Bharadwajshivam28** [comment]
is it looking good sir @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-08 12-52-27

**Comment by Bharadwajshivam28** [comment]
or any one from these @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-08 15-21-40

**Comment by Bharadwajshivam28** [comment]
I think this is looking perfect sir @swapnilsparsh

**Comment by swapnilsparsh** [comment]
> I think this is looking perfect sir @swapnilsparsh

Sorry to say but it's not looking good

**Comment by Bharadwajshivam28** [comment]
ok sir @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
sir basically can you give me some color hints like which you want i will try on every and get the perfect one @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-09 00-24-38
Screenshot from 2023-02-09 00-25-30
Screenshot from 2023-02-09 00-26-14
Screenshot from 2023-02-09 00-27-04
Screenshot from 2023-02-09 00-27-56
Screenshot from 2023-02-09 00-28-53
Screenshot from 2023-02-09 00-30-09

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-09 00-15-49
Screenshot from 2023-02-09 00-16-42
Screenshot from 2023-02-09 00-18-54
Screenshot from 2023-02-09 00-20-52
Screenshot from 2023-02-09 00-21-58
Screenshot from 2023-02-09 00-22-44
Screenshot from 2023-02-09 00-23-32

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-08 15-21-40
Screenshot from 2023-02-09 00-10-32
Screenshot from 2023-02-09 00-11-53

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Comment the best one sir

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 You are not understanding the point, just by changing the colors, it wont make a big change. You have to work on evrything like colors, layout, fonts, and other various things

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 You are not understanding the point, just by changing the colors, it wont make a big change. You have to work on evrything like colors, layout, fonts, and other various things

Sir can you just simply give the list of thing's to be changed

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 You are not understanding the point, just by changing the colors, it wont make a big change. You have to work on evrything like colors, layout, fonts, and other various things

And refer me changes that should be applied form where like your need

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 You are not understanding the point, just by changing the colors, it wont make a big change. You have to work on evrything like colors, layout, fonts, and other various things

Can the text color and text style also be changed?

**Comment by swapnilsparsh** [comment]
> > @Bharadwajshivam28 You are not understanding the point, just by changing the colors, it wont make a big change. You have to work on evrything like colors, layout, fonts, and other various things
> 
> And refer me changes that should be applied form where like your need

That only you have to explore and get different ideas and make a new layout out of it

**Comment by swapnilsparsh** [comment]
> > @Bharadwajshivam28 You are not understanding the point, just by changing the colors, it wont make a big change. You have to work on evrything like colors, layout, fonts, and other various things
> 
> Can the text color and text style also be changed?

Not now, first focus on layout and colors

**Comment by Bharadwajshivam28** [comment]
ok sir @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
can it be like that two in one row and the link of project and github side by side  @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
basically it will be clean and new designed @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
like side of one project there will be animated type for github link and project link @

**Comment by Bharadwajshivam28** [comment]
like in table format first side by side

**Comment by Bharadwajshivam28** [comment]
https://user-images.githubusercontent.com/108119109/217931324-9266f27c-0a41-4504-9235-f23a2b1a3340.mp4

**Comment by Bharadwajshivam28** [comment]
PLease review it sir is this layout good ? @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
The dark mode ,search bar everything will be added @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
Background color will also be made good

**Comment by Bharadwajshivam28** [comment]
JUst i am asking that is this layout fine so if you agree than will move forward @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
Basically my Target is to make each box flip with good background color combo @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
I will also make best background combo with flip box each box will flip and at the back of box there will be GitHub link of that project @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 Loooking quite good, but you have to use some border radius and center alignment with good color combination and font should be professional. Don't flip the box instad use the current card which is there showing project name with github logo and add a Link icon with link to that project

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh  sir but adding a Link icon with link to that project is good but sir one can acess the project just by clicking the box also

**Comment by Bharadwajshivam28** [comment]
so can i make a icon with link to project and remove the acess by clicking to the box

**Comment by Bharadwajshivam28** [comment]
like user will get to project by clicking on link icon not by  clicking on box

**Comment by Bharadwajshivam28** [comment]
or can you just elaborate these lines  "Don't flip the box instad use the current card which is there showing project name with github logo and add a Link icon with link to that project "  @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Sir i got your point

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh But sir can you just elaborate these lines "Don't flip the box instad use the current card which is there showing project name with github logo and add a Link icon with link to that project "

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh But sir can you just elaborate these lines "Don't flip the box instad use the current card which is there showing project name with github logo and add a Link icon with link to that project "

Use the cards which is there in current design as it is withour the flip animation

**Comment by Bharadwajshivam28** [comment]
ok

**Comment by Bharadwajshivam28** [comment]
https://user-images.githubusercontent.com/108119109/218175470-825423d1-93d2-451b-94bf-47963b9262bb
Screenshot from 2023-02-11 00-18-02
.mp4

**Comment by Bharadwajshivam28** [comment]
https://user-images.githubusercontent.com/108119109/218175630-53885f53-4e06-4944-bd06-2a7ff18755e5.mp4

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-11 00-18-02

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Hello sir as per your need  :- 

1)  made an link icon which refers to the project
2)hover effect

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh  Hello sir as per your need :-

   1) made an link icon which refers to the project
    2)hover effect
   3)rounded border
  4)center alignment

**Comment by Bharadwajshivam28** [comment]
After your approval sir i will move next for background colors and colors combination @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Just need a short review that till now is it good because till now no color is set .After your approval will move to those

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 Great work, go ahead for color combination

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 Great work, go ahead for color combination

Ok sir thanks

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 Great work, go ahead for color combination

Can you drop your background color combination which you like or should I explore the color combinations?

**Comment by swapnilsparsh** [comment]
> 

Explore on this website coolors.co
Choose some dark and light combo which goes well with each other as dark/light mode both are there on the website.

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 
> Explore on this website [coolors.co](https://coolors.co/)
> Choose some dark and light combo which goes well with each other as dark/light mode both are there on the website.

Ok sir

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 
> Explore on this website [coolors.co](https://coolors.co/)
> Choose some dark and light combo which goes well with each other as dark/light mode both are there on the website.

After color combinations which changes more sir needed ?

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Sir I am little bit confused in colors like i applied and i liked many combo

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh so can you drop your best 4-5 combo

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-11 18-15-19
Screenshot from 2023-02-11 18-18-04
Screenshot from 2023-02-11 18-19-34
Screenshot from 2023-02-11 18-20-12
Screenshot from 2023-02-11 00-18-02
Screenshot from 2023-02-11 18-05-13
Screenshot from 2023-02-11 18-08-47
Screenshot from 2023-02-11 18-13-21

Screenshot from 2023-02-11 18-20-57

**Comment by Bharadwajshivam28** [comment]
I have dropped some Samples so if you like then comment out  @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
I liked these combo

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 go for the black color with white in light mode and fix that input border line which is there to search for projects.

Make it responsive for all screens also.

**Comment by Bharadwajshivam28** [comment]
ok sir @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Done with these sir

1 ) Made it responsive for all screens
2)color also fixed
3) border line also fixed

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh SIr the search box border is looking very good in red color like border red . It is very impressive in red border in both the modes dark and light

**Comment by Bharadwajshivam28** [comment]
so if you agree then red border will be best for search box

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 Commit those changes so I can check them out live

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by Bharadwajshivam28** [comment]
doing it

**Comment by Bharadwajshivam28** [comment]
sir one last thing that search box border is looking best in red color

**Comment by Bharadwajshivam28** [comment]
red is looking best in both modes red border

**Comment by Bharadwajshivam28** [comment]
let me drop ss

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh SIr please check one new pr because by mistake i have pushed into master branch

**Pull request closed without merging**
