### PR TITLE
41 - Add new project to show a basic carousel/slider of images.

### PR DESCRIPTION
**Pull request by alexventuraio**
- Add new project to show a basic images slider.
- Add reference to the README file.
- Add the new entry in the main `index.html` file.

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@alexventuraio Please resolve the conflicts.

**Comment by alexventuraio** [comment]
> @alexventuraio Please resolve the conflicts.

@swapnilsparsh addressed!

**Comment by swapnilsparsh** [comment]
@alexventuraio Please resolve the conflicts and update.😅

**Comment by swapnilsparsh** [comment]
@alexventuraio All the PR has been merged, resolve this also so I can merge this PR also.🚀

**Comment by alexventuraio** [comment]
> @alexventuraio All the PR has been merged, resolve this also so I can merge this PR also.🚀

@swapnilsparsh all good now! 😎

**Comment by swapnilsparsh** [comment]
@alexventuraio Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Pull request merged**
