### PR TITLE
44 - Add project with Infinite Scroll example.

### PR DESCRIPTION
**Pull request by alexventuraio**
New project to show a basic example for infinite scroll.

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@alexventuraio Please resolve the conflicts.

**Comment by alexventuraio** [comment]
> @alexventuraio Please resolve the conflicts.

@swapnilsparsh addressed!

**Comment by swapnilsparsh** [comment]
@alexventuraio Please resolve the conflicts.😅

**Comment by alexventuraio** [comment]
> @alexventuraio Please resolve the conflicts.😅

@swapnilsparsh one more, up-to-date! 👍

**Comment by swapnilsparsh** [comment]
> > @alexventuraio Please resolve the conflicts.sweat_smile
> 
> @swapnilsparsh one more, up-to-date! +1

I merged your PR #34 and then now conflicts has to be resolved kn this PR 🙃

**Comment by alexventuraio** [comment]
> > > @alexventuraio Please resolve the conflicts.sweat_smile
> > 
> > 
> > @swapnilsparsh one more, up-to-date! +1
> 
> I merged your PR #34 and then now conflicts has to be resolved kn this PR 🙃

@swapnilsparsh  No worries, I'll be here until we get this done!

**Comment by alexventuraio** [comment]
> > > > @alexventuraio Please resolve the conflicts.sweat_smile
> > > 
> > > 
> > > @swapnilsparsh one more, up-to-date! +1
> > 
> > 
> > I merged your PR #34 and then now conflicts has to be resolved kn this PR 🙃
> 
> @swapnilsparsh No worries, I'll be here until we get this done!

@swapnilsparsh  Ready for you to review! 😎

**Comment by swapnilsparsh** [comment]
@alexventuraio Thank you for your contribution. Looking forward to more such amazing contributions 🌟

**Pull request merged**
