### PR TITLE
Project - Notes Taking App Added

### PR DESCRIPTION
**Pull request by Atharv-110**
#### Please Accept My PR for GSSoC'22.

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great project
Update the project number and details as Project Number 50 has already been added.

**Comment by Atharv-110** [comment]
Hey @swapnilsparsh can you tell me which number should I put?

**Comment by swapnilsparsh** [comment]
> Hey @swapnilsparsh can you tell me which number should I put?

Currently, 51 is there, you can update it to 52 but if someone else makes a PR before you then 52 will be there so be active and keep your eye on the repo so that you will know which number is there.

**Comment by Atharv-110** [comment]
Okay I am updating to 52 just now only.

**Comment by swapnilsparsh** [comment]
> Okay I am updating to 52 just now only.

52 has been updated, make it to 53

**Comment by Atharv-110** [comment]
Okay okay I'll do it to 53

**Comment by Atharv-110** [comment]
#### @swapnilsparsh I've updated my project to 53 please review it and merge my PR.

**Pull request merged**
