### PR TITLE
Conflicts Resolved

### PR DESCRIPTION
**Pull request by amanverma21**
I have resolved the conflicts, Kindly see to it

### CODE REVIEW

**Comment by amanverma21** [comment]
image

**Comment by swapnilsparsh** [comment]
@amanverma21 Responsive is not working fine on Small and Medium Screen, please fix this.

**Comment by amanverma21** [comment]
image

**Comment by amanverma21** [comment]
> > @swapnilsparsh Actually Sir this PR was for Calculator and it was working fine and you merged too, so can you please give hacktoberfest-accepted label to this one.
> 
> Check-in Files changes section there you will see you have added Age Calculator files also that's why I am asking you to make the Age Calculator responsive.

Sir the commits were visible but since u merged the changes only latest commit is merged, so that's not a issue i guess.

**Comment by swapnilsparsh** [comment]
> > > @swapnilsparsh Actually Sir this PR was for Calculator and it was working fine and you merged too, so can you please give hacktoberfest-accepted label to this one.
> > 
> > 
> > Check-in Files changes section there you will see you have added Age Calculator files also that's why I am asking you to make the Age Calculator responsive.
> 
> Sir the commits were visible but since u merged the changes only latest commit is merged, so that's not a issue i guess.

Oh, Sorry my bad.😅

**Comment by amanverma21** [comment]
Thanks a lot Sir, **looking forward for more such contribution from my side**

**Pull request merged**
