### PR TITLE
added candy crush

### LINKED ISSUE #1569: Title: Candy Crush Game purely using JS
### Is your feature request related to a problem? Please describe.

Adding popular mobile games as web applications would be quite a charm to website

### Describe the solution you'd like.

I will be using many inbuilt javascript methods such as:

- addEventListener()
- setAttribute()
- setInterval()
- some()
- every()
- forEach()
- includes()
- contains()
- add()
- remove()
- createElement()
- appendChild()
- push() 
to implement this game! 

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by AnanyaJain25**
### 🛠️ Fixes Issue (Number)

Close #1569

### 👨‍💻 Changes proposed and Brief Description

new game candy crush  added

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

Screenshot 2024-06-07 003827
Screenshot 2024-06-07 003844

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Remove the unnecessary package.json files

**Comment by AnanyaJain25** [comment]
hey @swapnilsparsh please reveiw it

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Add your project to index.html also and resolved the conflicts

**Comment by AnanyaJain25** [comment]
hey @swapnilsparsh everything is done please review

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Everything is working fine but when I am making 4 in total then there is some special candy which should be made. Follow the basic rules of candy crush

**Comment by AnanyaJain25** [comment]
> Everything is working fine but when I am making 4 in total then there is some special candy which should be made. Follow the basic rules of candy crush

the special candy feature cannot be implemented using only javascript

**Comment by swapnilsparsh** [comment]
> > Everything is working fine but when I am making 4 in total then there is some special candy which should be made. Follow the basic rules of candy crush
> 
> the special candy feature cannot be implemented using only javascript

Then I think there is no use to add it because you are missing out the basic rules.

**Comment by AnanyaJain25** [comment]
ok

**Pull request closed without merging**
