### PR TITLE
Windows 11 using JS

### PR DESCRIPTION
**Pull request by Mrjoy832**
hey! @swapnilsparsh, I have raised a PR on issue #362 , which is made using HTML5, CSS3, JS. 
**It Looks Like ->**
image

**Video Demo**

https://user-images.githubusercontent.com/77873383/160037009-12e1dad3-9856-4c1e-93c8-e8a815fb693b.mp4

### CODE REVIEW

**Comment by Mrjoy832** [comment]
@swapnilsparsh , Kindly Check it

**Comment by Mrjoy832** [comment]
@swapnilsparsh , why some checks are failed , and kindly check the PR.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh , why some checks are failed , and kindly check the PR.

I will have a look at this, thank you for pointing out the bug.

**Comment by swapnilsparsh** [comment]
@Mrjoy832 Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Pull request merged**
