### PR TITLE
Preloader added

### PR DESCRIPTION
**Pull request by samipak458**
### 👨‍💻 Changes proposed and Brief Description
I created a pre-loader for a 30DaysOfJavaScript website.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
I created a pre-loader using Html, CSS and JS.

### 📷 Screenshots

https://user-images.githubusercontent.com/52650290/166683365-65a336fe-609e-44fa-b77a-f0b727fe33b7.mp4

### CODE REVIEW

**Comment by samipak458** [comment]
@swapnilsparsh kindly review my PR. Thank you.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh kindly review my PR. Thank you.

It would be more great if you use anything related to JavaScript in preloader

**Comment by samipak458** [comment]
> > @swapnilsparsh kindly review my PR. Thank you.
> 
> It would be more great if you use anything related to JavaScript in preloader

Preloader is executing through Javascript. Can you give some example so I add more JS in preloader?

**Comment by samipak458** [comment]
Preloader updated

https://user-images.githubusercontent.com/52650290/167091388-d0f2e0e3-2d7b-4f27-9418-dfa616cf6603.mp4

**Pull request merged**
