### PR TITLE
Created a New Landing page

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Created a New Landing page

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh BY mistake i have pushed into the master branch instead of NEW-PAGE baranch

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 It is not responsive, check the below image 👇🏼
Test

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 Dark button and Search should be align with respect to heading.

**Comment by Bharadwajshivam28** [comment]
ok sir will correct it @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Sir i have fixed the overlapping issue and it is also responsive much

**Comment by Bharadwajshivam28** [comment]
sir the darkbutton is by default at little bit up in the page so its like that. IT is some up in page too

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 Not fixed yet, share the Screenshot

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 Not fixed yet, share the Screenshot

Sir it is fixed for screen

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 Not fixed yet, share the Screenshot

But sir alignment is not getting as in webpage dark icon is up so it is little bit up in all screen but the overlapping  of every thing is fixed

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 Not fixed yet, share the Screenshot

Sharing the ss

**Comment by swapnilsparsh** [comment]
> > @Bharadwajshivam28 Not fixed yet, share the Screenshot
> 
> Sir it is fixed for screen

Share the screenshot as when I am checking it is not showing as fixed.

**Comment by Bharadwajshivam28** [comment]
> > > @Bharadwajshivam28 Not fixed yet, share the Screenshot
> > 
> > Sir it is fixed for screen
> 
> Share the screenshot as when I am checking it is not showing as fixed.

Ok sir sharing the ss of overlapping

**Comment by swapnilsparsh** [comment]
> > > > @Bharadwajshivam28 Not fixed yet, share the Screenshot
> > > 
> > > 
> > > Sir it is fixed for screen
> > 
> > 
> > Share the screenshot as when I am checking it is not showing as fixed.
> 
> Ok sir sharing the ss of overlapping

Overlapping is fixed that I checked, I am asking for the alignment issue

**Comment by Bharadwajshivam28** [comment]
ok sir that will also be fixed

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Fixed the issue sir

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-14 13-15-23

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh At 320 dark button was going up and was not aligned but i fixed it

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh At 320 dark button was going up and was not aligned but i fixed it

You have changed the button by decreasing it with and its looking bad, like it's not the same button which was there previously

**Comment by Bharadwajshivam28** [comment]
> > @swapnilsparsh At 320 dark button was going up and was not aligned but i fixed it
> 
> You have changed the button by decreasing it with and its looking bad, like it's not the same button which was there previously 

Sir if dimensions is decreasing then some size decrease will also take place then it will fit in screen

**Comment by Bharadwajshivam28** [comment]
ok sir will fix it

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-15 18-56-03
Screenshot from 2023-02-15 18-58-55
9041615-6ba8952d-b6c3-4c0d-8782-395b2436c2f9.png)

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-15 18-56-03

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Fixed these sir

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 great efforts but you have to decrease the size of the button in such a way that it doesn't lose its original width and height.

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 great efforts but you have to decrease the size of the button in such a way that it doesn't lose its original width and height.

Sir can you elaborate

**Comment by swapnilsparsh** [comment]
> > @Bharadwajshivam28 great efforts but you have to decrease the size of the button in such a way that it doesn't lose its original width and height.
> 
> Sir can you elaborate 

You have fixed the button that is great but while achieving it you have reduce the width which is making it shrink so try to decrease equal width and height.

**Comment by Bharadwajshivam28** [comment]
> > > @Bharadwajshivam28 great efforts but you have to decrease the size of the button in such a way that it doesn't lose its original width and height.
> > 
> > Sir can you elaborate 
> 
> You have fixed the button that is great but while achieving it you have reduce the width which is making it shrink so try to decrease equal width and height.

Sir like in dimensions the width and height should be equal that it look good

**Comment by Bharadwajshivam28** [comment]
Like in dimensions of 320 it is getting stucked and because of that it is not looking good in 320 dimension

**Comment by Bharadwajshivam28** [comment]
So I have to make in dimensions such that it have equal and look good right?

**Comment by swapnilsparsh** [comment]
> So I have to make in dimensions such that it have equal and look good right?

Yes, both width and height shouble be same

**Comment by Bharadwajshivam28** [comment]
> > So I have to make in dimensions such that it have equal and look good right?
> 
> Yes, both width and height shouble be same
> 

Ok sir

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-16 19-12-40

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Fixed it sir

**Comment by swapnilsparsh** [comment]
Great Wok @Bharadwajshivam28 🎉🚀

**Comment by Bharadwajshivam28** [comment]
thanks sir @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
sir can you give me some community links which i can join

**Pull request merged**
