### PR TITLE
Add Pop_up

### PR DESCRIPTION
**Pull request by Lokeshsuwalka05**
### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

Please Review It @swapnilsparsh 

### 📷 Screenshots

one
two

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
@Lokeshsuwalka05 Instead of pop, don't allow the user to enter negative values.

**Comment by Lokeshsuwalka05** [comment]
> @Lokeshsuwalka05 Instead of pop up, don't allow the user to enter negative values.

Ok,Sir.

**Comment by Lokeshsuwalka05** [comment]
hello Sir @swapnilsparsh , please reveiw it.

**Comment by swapnilsparsh** [comment]
@Lokeshsuwalka05 Thank you for contributing to this repo. Looking forward for more 🚀

**Pull request merged**
