### PR TITLE
Add ecommerce template using html css and js

### PR DESCRIPTION
**Pull request by Samaresh-Das**
### 👨‍💻 Changes proposed and Brief Description

Added an eCommerce template of food menus at folder 204 where users can sort food items based on categories. 

### ✅ Check List (Check all the applicable boxes) 

- [ ] My code doesn't break any part of the project
- [ ] This PR does not contain plagiarized content.
- [ ] My Addition/Changes works properly and matches the overall repo pattern.
- [ ] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

I renamed my folder 204 as 203 is last folder before my pr gets approval.

### 📷 Screenshots

screencapture-file-E-PROJECTS-HACKTOBERFEST-2022-Ecommerce-Menu-index-html-2022-10-03-13_18_43

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
Not appropriate

**Comment by Samaresh-Das** [comment]
Can you suggest me any other project then? I really  want to make  project here. Not super complex though.

**Comment by swapnilsparsh** [comment]
> Can you suggest me any other project then? I really want to make project here. Not super complex though.

Sorry I can't help you out with this but, you can look out for ideas on Google.

**Comment by Samaresh-Das** [comment]
Ok

**Pull request closed without merging**
