### PR TITLE
Casino Slot Machine Game

### PR DESCRIPTION
**Pull request by Mrjoy832**
> ISSUE:- **#200** 
Hey! @swapnilsparsh  , I am **TRIDIB BAG**, GSSOC'22 Contributor, created issue #200 
and I added->
       1. Well structured code of **Casino Slot Machine Game**
       2.  Beautiful **readme File** demonstrating all the details with proper documentation , images, videos.
   **Technologies used**: HTML,CSS, JS.
Please check and send further update.

### CODE REVIEW

**Comment by Mrjoy832** [comment]
@swapnilsparsh please check it.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Give a proper number to the project folder.
Rename your folder to "73 - Casino Slot Game Machine"

**Comment by Mrjoy832** [comment]
image
How to resolve it @swapnilsparsh

**Comment by Mrjoy832** [comment]
Hey @swapnilsparsh, updated the folder name...please check and merge

**Comment by swapnilsparsh** [comment]
@Mrjoy832 Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Pull request merged**
