### PR TITLE
Modal Generator

### PR DESCRIPTION
**Pull request by Divyansh1315**
Modal generator updated in new branch.

It will create a Modal using JS.

### CODE REVIEW

**Comment by Divyansh1315** [comment]
Kindly review my PR...😊

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Update the project number as project till 59 number is already there on the repo.
Also mention the issue number which is assigned to you else the PR will not be counted as the issue was not assigned to you.

**Comment by Divyansh1315** [comment]
Updated the project number kindly merge my PR.

**Comment by Divyansh1315** [comment]
I've made the PR under Add your OWN JS PROJECTS #4.

It is mentioned that no need to create a new issue to add a project.

**Comment by swapnilsparsh** [comment]
> I've made the PR under Add your OWN JS PROJECTS #4.
> 
> It is mentioned that no need to create a new issue to add a project.

There were some updates so first, you have to open the issue then get assigned after that make a PR.
Sorry for the inconvenience caused.

**Pull request closed without merging**
