### PR TITLE
Temperature Convertor Project Added

### PR DESCRIPTION
**Pull request by priyanshi1282**
### Please Accept my PR as a Contribution in GSSoC'22.

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great project
Update the project number as project till number 50 has been added.

**Comment by priyanshi1282** [comment]
Thanks @swapnilsparsh , Can you provide me the project number to which I should update?

**Comment by swapnilsparsh** [comment]
> Thanks @swapnilsparsh , Can you provide me the project number to which I should update?

Currently, 51 is there, you can update it to 52 but if someone else makes a PR before you then 52 will be there so be active and keep your eye on the repo so that you will know which number is there.

**Comment by priyanshi1282** [comment]
> @priyanshi1282 Thank you for your contribution. Looking forward to more such amazing contributions 🥂

Thank you @swapnilsparsh 🤩.

**Pull request merged**
