### PR TITLE
Car game

### LINKED ISSUE #333: car Game
### Is your feature request related to a problem? Please describe.

Car game using html ,CSS , JS

### Describe the solution you'd like.

Using basic concepts of js

### Describe alternatives you've considered.

To further improve game in design and features

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by nitishsaini706**
Fixed #333 
Created simple game using HTML , CSS ,JS
will add more functionalities and features to the game for now it's a simple game

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
1. Resolve the conflicts
2. Update the project number to 76

**Comment by nitishsaini706** [comment]
Okk sure

**Comment by nitishsaini706** [comment]
@swapnilsparsh I added the changes you asked for and resolved the conflicts occured

**Comment by swapnilsparsh** [comment]
@nitishsaini706 Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Pull request merged**
