### PR TITLE
Tower of Hanoi Game

### PR DESCRIPTION
**Pull request by Praneeth-2602**
### 👨‍💻 Changes proposed and Brief Description

Added the tower of hanoi game

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

image

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Add your project to index.html also

**Comment by Praneeth-2602** [comment]
Added screenshot to the assets folder and item to the index.html file sir.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Photo not showing 
image

**Comment by Praneeth-2602** [comment]
image
Screenshot 2024-05-29 161059

It is fixed @swapnilsparsh sir!

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Game is not finishing when I complete it in middle rod. But it gets finished in last rod.
image

**Comment by Praneeth-2602** [comment]
But if u insist.. I shall work on it

**Comment by Praneeth-2602** [comment]
Done as directed @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@Praneeth-2602 Thank you for contributing to this repo. Looking forward for more 🚀

**Pull request merged**
