### PR TITLE
Added Movie Search App

### PR DESCRIPTION
**Pull request by Atif0604**
Fix : #205

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Resolve the conflicts
Update your project folder name to the project number which is not available on the repo yet.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Update your project folder name to the project number which is not available on the repo yet.

**Comment by Atif0604** [comment]
> Update your project folder name to the project number which is not available on the repo yet.

Hey @swapnilsparsh I tried doing the same but i wasn't able to do because some path error with is (error: invalid path '63 - Quotes Generator) which was there before also while resolving the conflicts but anyhow i did it but now i'm helpless with this error , i tried doing everything(reset rebase stash) but non of them worked

so if possible could you please merge it as it is , i will do this renaming in some other issue/PR

**Comment by swapnilsparsh** [comment]
> 

It is not possible to merge it as you have not named the folder which is a required step and if I will merge your PR then it will be unfair for others.

**Comment by swapnilsparsh** [comment]
> > Update your project folder name to the project number which is not available on the repo yet.
> 
> Hey @swapnilsparsh I tried doing the same but i wasn't able to do because some path error with is (error: invalid path '63 - Quotes Generator) which was there before also while resolving the conflicts but anyhow i did it but now i'm helpless with this error , i tried doing everything(reset rebase stash) but non of them worked
> 
> so if possible could you please merge it as it is , i will do this renaming in some other issue/PR

It is not possible to merge it as you have not named the folder which is a required step and if I will merge your PR then it will be unfair for others.

**Comment by Atif0604** [comment]
> > > Update your project folder name to the project number which is not available on the repo yet.
> > 
> > 
> > Hey @swapnilsparsh I tried doing the same but i wasn't able to do because some path error with is (error: invalid path '63 - Quotes Generator) which was there before also while resolving the conflicts but anyhow i did it but now i'm helpless with this error , i tried doing everything(reset rebase stash) but non of them worked
> > so if possible could you please merge it as it is , i will do this renaming in some other issue/PR
> 
> It is not possible to merge it as you have not named the folder which is a required step and if I will merge your PR then it will be unfair for others.

So if you can help me with the solution of this error ,as i tried every thing to do

**Pull request closed without merging**
