### PR TITLE
Guess the Number

### LINKED ISSUE #207: Guess the Number Game
Myself Ishita Bisaria,
I have built a web game, Guess the Number, its a fun game and I want to add it in this repository.
Kindly assign this issue to me.
Thanking you.

### PR DESCRIPTION
**Pull request by IshitaBisaria**
Myself Ishita Bisaria
I am a contributor at GSSOC '22
I made a fun game of Guess the Number.
Fixes #207

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Update the project number as project till 59 number is already there on the repo.

**Comment by IshitaBisaria** [comment]
Updated the Project number to 60

**Comment by IshitaBisaria** [comment]
Kindly review and merge the PR

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Update the project number as project till 64 number is already there on the repo.

**Comment by IshitaBisaria** [comment]
Updated the Project number to 66

**Comment by IshitaBisaria** [comment]
Kindly review the PR.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Updated the Project number

**Comment by IshitaBisaria** [comment]
Updated the Project number!!
Kindly review the PR

**Pull request merged**
