### PR TITLE
New web

### LINKED ISSUE #1377: [Feature] your website is need makeover
### Is your feature request related to a problem? Please describe.

Hello @swapnilsparsh,

I’ve taken a look at your website and I believe it has great potential. I would like to offer my services to revamp it and enhance its user-friendliness. I’m eager to undertake this project as part of **GSSoC 2024.** **Please consider assigning this task to me.**

### Describe the solution you'd like.

**User Experience Audit**: Conduct a thorough review of the current website to identify areas that can be improved for better user engagement and ease of use.
**Design Overhaul:** Implement a modern, clean design that aligns with your brand and improves the overall aesthetic appeal.
**Navigation and Structure**: Simplify the navigation to ensure that users can find information quickly and intuitively.

### Describe alternatives you've considered.

Template-Based Redesign: Instead of a custom design, you could opt for a high-quality, pre-designed template. This can be a cost-effective and time-saving option, though it might limit customization.

### PR DESCRIPTION
**Pull request by pandeyji711**
### 🛠️ Fixes Issue (#1377 )

Closes #1377 

@swapnilsparsh  your website as you wanted .

### ✅ Check List (Check all the applicable boxes) 

- [ X] My code doesn't break any part of the project
- [X ] This PR does not contain plagiarized content.
- [X ] My Addition/Changes works properly and matches the overall repo pattern.
- [ X] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
Screenshot 2024-05-20 152536

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/154527778/f595f8d8-05a7-48e0-b378-8ced172e729f

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
I asked you to make the UI like it is shown in below photo but you have not make it like that so can you fix it.

image

**Comment by pandeyji711** [comment]
@swapnilsparsh ok

**Comment by pandeyji711** [comment]
@swapnilsparsh is this correct
#red shadow on hover
Screenshot 2024-05-21 022236

**Comment by pandeyji711** [comment]
@swapnilsparsh please cheak this

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Yes it is looking better just remove the hover animation and fix the button size.

**Comment by pandeyji711** [comment]
@swapnilsparsh I modified web page as instructed and add all **112 games** 

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/154527778/07fa5f54-3c11-4630-a4f3-c626af4a5bae

**Comment by pandeyji711** [comment]
@swapnilsparsh please mark this  **Gssoc and level 3**

**Comment by pandeyji711** [comment]
@swapnilsparsh please review and merge with Gssoc and level 3 label

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
1. When build is made then no image is showing which is because you are using "/" in defining the image path which you don't have to do. Correct solution is to use like this "30DaysOfJavaScript/30DaysOfJavaScript/assets/02.png"

2. You don't have to define onClick on every button as you have to use <a> tag instead

3. Don't remove other things from design like search and footer beside this everything is fine.

**Comment by swapnilsparsh** [comment]
@pandeyji711 
image

**Comment by pandeyji711** [comment]
@swapnilsparsh ok

**Comment by pandeyji711** [comment]
now img is working fine 
Screenshot 2024-05-23 135909

**Comment by pandeyji711** [comment]
@swapnilsparsh all changes are done please review
Screenshot 2024-05-23 161442

**Comment by pandeyji711** [comment]
@swapnilsparsh please review and merge

**Comment by pandeyji711** [comment]
@swapnilsparsh ### please review and merge with Gssoc and level 3 label

**Comment by pandeyji711** [comment]
@swapnilsparsh please review this

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Still this is not fixed (You don't have to define onClick on every button as you have to use <a> tag instead)
image

You don't have to remove pagination.

**Comment by pandeyji711** [comment]
@swapnilsparsh please review i have fixed the  issue

**Comment by swapnilsparsh** [comment]
> Still this is not fixed (You don't have to define onClick on every button as you have to use tag instead) image
> 
> You don't have to remove pagination.

Still this is not fixed. @pandeyji711

**Comment by pandeyji711** [comment]
@swapnilsparsh ok gotit fixing pagination

**Comment by pandeyji711** [comment]
@swapnilsparsh please review i implimented all the  changes that you asked for and mark it for Gssoc24 level 3 
fix #1377 
Screenshot 2024-05-28 002129

**Comment by pandeyji711** [comment]
@swapnilsparsh please review

**Comment by pandeyji711** [comment]
@swapnilsparsh please review and merge , mark Gssoc 24 level 3

**Comment by swapnilsparsh** [comment]
@pandeyji711 Everything is working fine just fix this 
image

**Comment by swapnilsparsh** [comment]
@pandeyji711 Also the footer should stick to bottom
image

**Comment by pandeyji711** [comment]
@swapnilsparsh    Ok

**Comment by swapnilsparsh** [comment]
@pandeyji711 Footer is not fixed yet and resolve the conflicts also where every project description is added.
image

**Comment by pandeyji711** [comment]
@swapnilsparsh I created Pr with other branch https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/1559 
becouse this gives conflict

**Pull request closed without merging**
