### PR TITLE
FIXED COUNTDOWN TIMER

### PR DESCRIPTION
**Pull request by ananyakushal**
### ✅ Check List (Check all the applicable boxes) 

- [ ] My code doesn't break any part of the project
- [ ] This PR does not contain plagiarized content.
- [ ] My Addition/Changes works properly and matches the overall repo pattern.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
@ananyakushal Check your changes [here](https://deploy-preview-1010--30daysofjs.netlify.app/16%20-%20countdown%20timer/)

When Page gets load up then Start button is not showing disabled and also when I am setting up the time and clicking on start button the timer is not getting started.

Test

**Comment by ananyakushal** [comment]
Ok @swapnilsparsh, I will work on it.

**Comment by ananyakushal** [comment]
countdown timer
I have disabled start button when the time has not been setup and also added a subheading "Set Your Timer" below the main heading.

**Comment by swapnilsparsh** [comment]
@ananyakushal Great, I have tested and it's working but there are some bugs that has to be fixed.
As there are few more changes to be done so I have changed the issue level from EASY -> MEDIUM 

1. When timer reaches zero and I increase the time then also it gets keep on wokring that should not be the case as when timer reaches zero then it should again disable the start button
2. Add a pause button which will only appear when you hit the start button
3. Also restart button will only show when you start the timer else dont show it.
4. When you hit the start button then it should gets disabled

**Comment by ananyakushal** [comment]
@swapnilsparsh I have made the required changes. Hope you will like it.

**Comment by swapnilsparsh** [comment]
@ananyakushal Great work 🚀

**Comment by ananyakushal** [comment]
@swapnilsparsh Thank You. It was great working with you.

**Pull request merged**
