### PR TITLE
Luminosity particle js effect

### PR DESCRIPTION
**Pull request by yash-25log**
### 🛠️ Fixes Issue (Number)
#566 

### 👨‍💻 Changes proposed and Brief Description
used HTML CSS js and particle js along with maths
colorized form for particle js
work effectively on mouseover

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
image

https://user-images.githubusercontent.com/58944204/164973029-3f87ef2c-a269-4c8c-8c4a-f76eebadee44.mp4

### CODE REVIEW

**Comment by yash-25log** [comment]
@swapnilsparsh pls check this pr

**Comment by yash-25log** [comment]
@swapnilsparsh bhaiya i am sorry i was unable to record interactivity tho it is interactive
my recorder wasn't recording it idk why

**Comment by yash-25log** [comment]
if you say i can host it and share link

**Comment by swapnilsparsh** [comment]
Resolve the conflict

**Comment by yash-25log** [comment]
> Resolve the conflict

oh i ddin't saw it
will do soon

**Pull request closed without merging**
