### PR TITLE
Added Functionality of Manual Selection of City/Country

### PR DESCRIPTION
**Pull request by amanverma21**
Now we can **manually select the city** of which we want to check the weather.

### CODE REVIEW

**Comment by amanverma21** [comment]
image

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
It's working great but the background is not changing according to the weather it is the feature that was added in the #59 
Please resolve this.

**Comment by amanverma21** [comment]
image
image

**Comment by amanverma21** [comment]
Thank you for your contribution. Looking forward to more such amazing contributions 🥂

Thanks a lot!!

**Pull request merged**
