### PR TITLE
Added screenshots and changed layout

### PR DESCRIPTION
**Pull request by piyushmishraa**
I changed the layout slightly by giving repo list a tabular form of 3 columns so that visitors don't have to scroll down for long time and they can see the list in of 30 projects in one go
I also added screenshots of some of your projects that looked really good visually 

I hope you like it :)
Also if you have any suggestions, you can tell me and i'll be more than happy to work on them.
THANKS

### CODE REVIEW

**Comment by piyushmishraa** [comment]
@swapnilsparsh sir i have opened a pull request but a warning seems to appears where it says 2 workflows awaiting approval.
I am new to open source. can you  please guide me what's happening here?

**Comment by swapnilsparsh** [comment]
@piyushmishraa Provide the screenshots of the changes that you have made here.

**Review by nerdy-nakul — APPROVED** [review]

**Comment by piyushmishraa** [comment]
sample Screenshot
sample Screenshot4

sample Screenshot6
er-images.githubusercontent.com/116213566/216359112-58d8cf69-117d-4b3c-b1a0-191be8089bb6.png)
images.githubusercontent.com/116213566/216359086-c6e85677-450b-4a9c-b752-8e542eac477d.png)

sample Screenshot3

sample Screenshot2
@swapnilsparsh sir here are the screenshots

**Comment by piyushmishraa** [comment]
sample Screenshot
sample Screenshot6
sample Screenshot7

sample Screenshot5

sample Screenshot3
sample Screenshot4

sample Screenshot2

**Comment by swapnilsparsh** [comment]
@piyushmishraa Remove the screenshots from the Readme

**Comment by piyushmishraa** [comment]
Got it

**Comment by piyushmishraa** [comment]
@swapnilsparsh removed them 👍

**Comment by swapnilsparsh** [comment]
@piyushmishraa Remove the files also

**Comment by piyushmishraa** [comment]
@swapnilsparsh sorry sir i totally forgot about it.
Removed them.

**Pull request merged**
