### PR TITLE
Added project on BMI_Calculator

### PR DESCRIPTION
**Pull request by maheshdbabar9340**

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Update the project number as project till 64 number is already there on the repo.

**Comment by maheshdbabar9340** [comment]
> Update the project number as project till 64 number is already there on the repo.

Where is the project number? I will update it as you told.

**Comment by swapnilsparsh** [comment]
> > Update the project number as project till 64 number is already there on the repo.
> 
> Where is the project number? I will update it as you told.

Update the Project number as 66 is already there.

**Comment by maheshdbabar9340** [comment]
> > > Update the project number as project till 64 number is already there on the repo.
> > 
> > 
> > Where is the project number? I will update it as you told.
> 
> Update the Project number as 66 is already there.

where i should update?

**Comment by swapnilsparsh** [comment]
> > > > Update the project number as project till 64 number is already there on the repo.
> > > 
> > > 
> > > Where is the project number? I will update it as you told.
> > 
> > 
> > Update the Project number as 66 is already there.
> 
> where i should update?

Folder name

**Pull request closed without merging**
