### PR TITLE
fix #1636: Repeating image issue is fixed

### LINKED ISSUE #1636: [Bug] : Image is getting repeated in Image Utility (49)
### What happened?

While using the Image Utility (49) App, I found that as soon as I upload an image that is not an square. The image is getting repeted within the workspace

### How can we reproduce this bug?

This bug can be produced just by uploading an image. PS. The image should be a rectangular one (not a square one).

Screenshot (336)

### Desktop Information (Optional)

Device: Laptop
OS: Windows 11 Home
Browser: Chrome

### Urgency (Optional)

Medium priority

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by mondalsurojit**
### 👨‍💻 Changes proposed and Brief Description
📌 Since bootstrap was used in the previous version with some css, there were several conflicting styles between the two, so I decided to removed all the bootstrap and rewrote the entire css. During this process, I have updated the entire User Interface
📌 The repeating image problem is fixed
📌 The reset button is fixed
📌 Added download button, which can be used either to download or to share the image directly from the application
📌 Added zoom/full screen feature in the image
📌 Made the entire site responsive

### ✅ Check List (Check all the applicable boxes) 

- [X] My code doesn't break any part of the project
- [X] This PR does not contain plagiarized content.
- [X] My Addition/Changes works properly and matches the overall repo pattern.
- [X] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

@swapnilsparsh Please review my PR...I have to put a lot of effort to fix the entire application. I thought that rather than opening several small-small issues to fix minute problems, why not just fix/rebuilt the entire application and make a good PR...I hope this will be qualified to be a level 3 PR

## Video
[Demo](https://youtu.be/OYTu9h1bgHg?si=_CggTfLTl-PVZ_u0)

## Screenshots
Screenshot 1
Screenshot 2

**Image before editing**
Screenshot 3

**Image after editing**
Screenshot 4

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Don't make changes in other project folder files.

**Comment by mondalsurojit** [comment]
@swapnilsparsh o..sorry, actually I didn't intended to do changes in other files...somehow when I merged the working branch with the upstream branch...this thing happened...I am fixing it right now...

**Comment by mondalsurojit** [comment]
@swapnilsparsh I have fixed it....please check once...

**Comment by swapnilsparsh** [comment]
@mondalsurojit Thank you for contributing to this repo. Looking forward for more 🚀

**Pull request merged**
