### PR TITLE
Vowel Counter 

### PR DESCRIPTION
**Pull request by Divyansh1315**
A vowel counter using JS. 

You can enter any word and it will give the result as calculated no. of the vowel in that word.

### CODE REVIEW

**Comment by Divyansh1315** [comment]
Kindly Review my PR..😊

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great Project
Update the project number as project number 55 has already been added to the repo.

**Comment by Divyansh1315** [comment]
Project Number updated as directed.

Thank you...😊

**Comment by Divyansh1315** [comment]
t

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Update the project number as project till 59 number is already there on the repo.
Also mention the issue number which is assigned to you else the PR will not be counted as the issue was not assigned to you.

**Comment by Divyansh1315** [comment]
I've made the PR under Add your OWN JS PROJECTS https://github.com/swapnilsparsh/30DaysOfJavaScript/issues/4.

It is mentioned that no need to create a new issue to add a project.

**Comment by swapnilsparsh** [comment]
> I've made the PR under Add your OWN JS PROJECTS #4.
> 
> It is mentioned that no need to create a new issue to add a project.

There were some updates so first, you have to open the issue then get assigned after that make a PR.
Sorry for the inconvenience caused.

**Pull request closed without merging**
