### PR TITLE
Subharthi

### PR DESCRIPTION
**Pull request by splusb**
I have modified the dice rolling problem which shows two players and also declares who wins after one shuffle.

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@splusb Great idea, create a seperate folder for this project and name it as it is a new project whereas current dice roller is only for 1 dice and 1 player

**Comment by splusb** [comment]
As per the suggestion, a new file is created for the game with two players, and the previous game with one player is remaining as it was.

**Comment by swapnilsparsh** [comment]
@splusb  Please create a sepearte folder naming a different project and there add your file

**Comment by splusb** [comment]
Hi, I have created a folder with a diff name "Dice Roll with two players".

**Pull request closed without merging**
