### PR TITLE
Update UI of the Body Mass Index Calculator with full working and responsvie

### PR DESCRIPTION
**Pull request by vinitsingh-13**
image
 -->

### CODE REVIEW

**Comment by vinitsingh-13** [comment]
with hover effect on the button

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Still not responsive
image

**Comment by vinitsingh-13** [comment]
> Still not responsive image
 sorry if this

**Comment by vinitsingh-13** [comment]
Sorry for this I am going to overview this project again and fix it

**Comment by swapnilsparsh** [comment]
@vinitsingh-13 Dont make new folder, make changes in the current folder only.

**Comment by vinitsingh-13** [comment]
i had made the change you can merge the branch

**Comment by swapnilsparsh** [comment]
@vinitsingh-13 You haven't made the commit yet I guess. Make a commit and let me know.

**Comment by swapnilsparsh** [comment]
@vinitsingh-13 You have to make it responsive for every possible screen.

**Comment by vinitsingh-13** [comment]
> @vinitsingh-13 You have to make it responsive for every possible screen.
ok bro i will try to do that because below the 300px the font size become very small and that does not look good

**Review by vinitsingh-13 — COMMENTED** [review]
this is the changes i have made in the style.css file now this is fully responsive website which will work in every phone and at every breakpoint

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Why you have deleted the previous folder ? Due to this it will affect the main website. Dont make new folder.

**Comment by vinitsingh-13** [comment]
> Why you have deleted the previous folder ? Due to this it will affect the main website. Dont make new folder.

i had only made a new style sheet file in the same folder so that will not affect the website so you can merge the request with it

**Pull request closed without merging**
