### PR TITLE
66 - Projectile-Motion_Simulator

### PR DESCRIPTION
**Pull request by waleedhesham446**
I have added my own JS project which is a simple simulator to the projectile motions, it was created for an educational purposes and gained a lot of respect from my mentors. Project number is 66.
pms

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Updated the Project number as 66 is already there.

**Comment by waleedhesham446** [comment]
What is the number of my project to <script>console.log(1)</script> change it

**Comment by waleedhesham446** [comment]
<Script>alert("1")</Script>

**Comment by waleedhesham446** [comment]
"-prompt(8)-"

**Comment by waleedhesham446** [comment]
'-prompt(8)-'

**Comment by swapnilsparsh** [comment]
> What is the number of my project to change it

84

**Comment by waleedhesham446** [comment]
but 84 is already occupied, what about 87 ?

**Comment by swapnilsparsh** [comment]
> but 84 is already occupied, what about 87 ?

88 ✅

**Comment by waleedhesham446** [comment]
Done bro

**Comment by waleedhesham446** [comment]
I have made another pull request

**Pull request merged**
