### PR TITLE
Added Pair Making Game

### PR DESCRIPTION
**Pull request by shubham-sharma-2323**
added the pair making game to the repository for the issue #741

### CODE REVIEW

**Comment by shubham-sharma-2323** [comment]
@swapnilsparsh why didn't you merged my PR ?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh why didn't you merged my PR ?

The issue was not assigned to you.

**Comment by shubham-sharma-2323** [comment]
> > @swapnilsparsh why didn't you merged my PR ?
> 
> The issue was not assigned to you.

Yes ik but why haven't you assigned it ? You just simply closed the issue

**Comment by swapnilsparsh** [comment]
> > > @swapnilsparsh why didn't you merged my PR ?
> > 
> > 
> > The issue was not assigned to you.
> 
> Yes ik but why haven't you assigned it ? You just simply closed the issue

Because this type of project is already there on the repo

**Pull request closed without merging**
