### PR TITLE
Doodle

### LINKED ISSUE #1568: Title: Doodle Jump Game
### Is your feature request related to a problem? Please describe.

We might need more exciting adn kind of addictive games which involves visible movements!

### Describe the solution you'd like.

Doodle Jump is a popular and addictive game known for its simple yet engaging mechanics, which can attract a wide audience. By incorporating this game, we can create a more captivating and enjoyable experience for our users

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

will implement this popular game 
Screenshot 2024-05-30 151954

### PR DESCRIPTION
**Pull request by AnanyaJain25**
### 🛠️ Fixes Issue (Number)

closes #1568

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/136808696/85be90ba-1717-4459-9cf5-1a0793ce425f

Screenshot 2024-06-07 011209

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
1. Very laggy while playing the game
2. Game should not start automatically instead start button should be there

**Comment by AnanyaJain25** [comment]
Please check now.

**Comment by AnanyaJain25** [comment]
hey @swapnilsparsh please review

**Comment by swapnilsparsh** [comment]
@AnanyaJain25 Check it [here](https://deploy-preview-1682--30daysofjs.netlify.app/120%20-%20doodle/), without controlling it is getting played and speed is very fast as it should gradually increase when you play along the game.

**Comment by AnanyaJain25** [comment]
> @AnanyaJain25 Check it [here](https://deploy-preview-1682--30daysofjs.netlify.app/120%20-%20doodle/), without controlling it is getting played and speed is very fast as it should gradually increase when you play along the game.

Sir without controlling it cannot be played there might be some combination of tiles which are consecutive which is why the doodle is jummping continously However i have done some changes and also added instruction panel now is it fine?

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/136808696/c55019be-e7c6-4dbc-9454-eed3a71f9fac

**Comment by AnanyaJain25** [comment]
> Spacing should be there to avoid automatic jump on different tiles.

that is random only ..sometimes they come closer in beginning and later you will get spaced also  sometimes from the beginning only those are spaced. I dont really understand the problem?

**Comment by AnanyaJain25** [comment]
> > @AnanyaJain25 Check it [here](https://deploy-preview-1682--30daysofjs.netlify.app/120%20-%20doodle/), without controlling it is getting played and speed is very fast as it should gradually increase when you play along the game.
> 
> Sir without controlling it cannot be played there might be some combination of tiles which are consecutive which is why the doodle is jummping continously However i have done some changes and also added instruction panel now is it fine?
> 
>  Doodle.Jump.-.Google.Chrome.2024-06-11.07-23-26.1.mp4
what exactly is the problem there are automatic jumps if the tile is just above another and that happen in the game also apart from it we have to move when tiles are apart

**Comment by swapnilsparsh** [comment]
> > Doodle.Jump.-.Google.Chrome.2024-06-11.07-23-26.1.mp4
> 
> what exactly is the problem there are automatic jumps if the tile is just above another and that happen in the game also apart from it we have to move when tiles are apart

You have to make a proper distance between two tiles to avoid automatic jump

**Comment by swapnilsparsh** [comment]
@AnanyaJain25 Any update ?

**Pull request closed without merging**
