### PR TITLE
New web1

### PR DESCRIPTION
**Pull request by pandeyji711**
@swapnilsparsh ### **this is new branch** 
🛠️ Fixes Issue (https://github.com/swapnilsparsh/30DaysOfJavaScript/issues/1377 )
Closes https://github.com/swapnilsparsh/30DaysOfJavaScript/issues/1377

@swapnilsparsh your website as you wanted .

✅ Check List (Check all the applicable boxes)
[ X] My code doesn't break any part of the project
[X ] This PR does not contain plagiarized content.
[X ] My Addition/Changes works properly and matches the overall repo pattern.
[ X] The title of my pull request is a short description of the requested changes.
### 📄Please mark Gssoc 24 and level 3
**All changes are successfully caried out**
Screenshot 2024-05-30 005413

### CODE REVIEW

**Comment by pandeyji711** [comment]
@swapnilsparsh please review and mark Gssoc24 and level 3

**Comment by pandeyji711** [comment]
@swapnilsparsh please review and merge

**Comment by pandeyji711** [comment]
@swapnilsparsh ###  pleaase review and merge

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Everything is working fine just provide some space around the website as now there is no space, it is sticked to the sides 

image

**Comment by pandeyji711** [comment]
@swapnilsparsh ok

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh ok

Resolve the conflicts also

**Comment by pandeyji711** [comment]
@ ok i will do it tomarrow

**Pull request closed without merging**
