### PR TITLE
Added a new javascript project - IP Address Tracker

### PR DESCRIPTION
**Pull request by VrindaTyagi**
Added a project - **IP Address Tracker** to the repo and **linked it to the website**.

**_Preview_**

- Home Page

image

Kindly review the changes.

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great Project
Resolve the conflicts
Update the project number as project number 54 has already been added to the repo.

**Comment by VrindaTyagi** [comment]
I have fixed the merge issues, kindly review the changes.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Update the project number as project till 59 number is already there on the repo.

**Comment by VrindaTyagi** [comment]
Updated the project number to 62 and added a transition effect to the theme toggle function. 
fixes #194

**Comment by swapnilsparsh** [comment]
@VrindaTyagi Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Pull request merged**
