### PR TITLE
Added a Postmaster Clone Using JavaScript

### PR DESCRIPTION
**Pull request by singhkunal01**
Hey @swapnilsparsh  this is my Final Project which I made using _JavaScript_.
### What It Is ?

- Basically it is similar to Postmaster or like a REST API Extension (VS Code).
- It helps You to fetch the data From API or Link you enters and display you in a well formatted way (For this I used Prism JS and Prism CSS)
- You can also post any Request Using Customizable Parameters.

### To check All things Please Take a trial

_**Any Problem , Let me know I'll fix it ASAP**_

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@singhkunal01 Update your project on the official website also in the 30DaysOfJS folder.

**Comment by singhkunal01** [comment]
Sorry but i'm little bit confused, Can please guide me for that because after fork i have make a repo named 51th number after that I Raise a pull request but still it is not shown here , what should i have to do exactly ?
Can i do the same directly by github page ?

**Comment by singhkunal01** [comment]
hey @swapnilsparsh  can you please help me for once i have completed my project and i stucked here in the last step only , so please try to resolve it so that i can move forward.

**Comment by swapnilsparsh** [comment]
> 

You have to pull the lastest changes of the repo and then you can update the number of your project.

**Comment by singhkunal01** [comment]
i did everything but don't know when i clicked on that deployed link it doesn't shows my project when i click on this deployed link https://github.com/singhkunal01/30DaysOfJavaScript/ what should i do , I know i'm missing something please let me know

**Comment by swapnilsparsh** [comment]
> i did everything but don't know when i clicked on that deployed link it doesn't shows my project when i click on this deployed link https://github.com/singhkunal01/30DaysOfJavaScript/ what should i do , I know i'm missing something please let me know

Can you please explain the problem which you are facing?

**Comment by swapnilsparsh** [comment]
Fixes #149

**Comment by singhkunal01** [comment]
Even I don't know what i have to do now to get my project merged because everything according to your documentation i did

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Just update the project number as project number 56 is already there on the repo.

**Comment by swapnilsparsh** [comment]
@singhkunal01 Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Pull request merged**
