### PR TITLE
Added my random anime profile pic generator to the list..

### PR DESCRIPTION
**Pull request by AmolShelke2**
hey, Project admin I'm a GSSOC participant and as you assign me the issue to work on that I create the project that I want to add my random anime profile pic generator to the list I complete the issue and now I'm creating the pull request regarding that I get busy due to my offline college so that's why it takes time to me, this project is very useful for those who don't have the knowledge of working with web API in javascript and how the fetch function works. and I'm attaching the screenshot and deployMent link please go through it and I hope that you will go through my pull request and merge it thanking you...

# DeployMent link 
[Random Anime profile](https://anime-app-tau.vercel.app/)

# ScreenShot
192 168 187 73_5501_Random%20Anime%20Profile%20Pic_index html

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Update the project number to 74

**Comment by AmolShelke2** [comment]
Okk

**Comment by AmolShelke2** [comment]
Updated the project number please give it.a look

**Comment by swapnilsparsh** [comment]
@AmolShelke2 Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Comment by anamansari062** [comment]
@AmolShelke2 This has already been made in another repo https://github.com/arpit456jain/Amazing-Js-Projects/pull/353

**Pull request merged**
