### PR TITLE
Project description placeholder is added

### LINKED ISSUE #1199: Title: Adding Project description to the listed projects
### Is your feature request related to a problem? Please describe.

The website lists many projects, but it's hard to understand what each one does without going to a separate GitHub repos for each project. It's too much work to visit so many sites!

Website : https://30daysofjs.netlify.app/

### Describe the solution you'd like.

Instead of making users visit separate GitHub repos, we can add short descriptions directly to the website. When someone holds their mouse over a project (hovers over it), the project description will appear on top of the slightly faded image. This way, users can learn about each project without needing to jump around to different websites.

### Describe alternatives you've considered.

The alternative approach is to add a `README.md` file for each project describing the project's functionalities.

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by Rupa-Rd**
### 🛠️ Fixes Issue (Number)
Closes #1199 

### 👨‍💻 Changes proposed and Brief Description
Project description placeholder is added for each project (up-to date). Whenever the user hovers their mouse over the project card, the project description will be shown by fading the background image.

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
I added only the placeholders for the project description.

### 📷 Screenshots
screen-capture (22)

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
If I hover then on whole project image the description is showing then how will I open that project ?

**Comment by Rupa-Rd** [comment]
> If I hover then on whole project image the description is showing then how will I open that project ?

I apologize for not noticing that issue. 
Can you check my commits now? The link for the Github repo and website can be accessed now.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Looks good just remove the lorem ispum and use correct description.

**Comment by swapnilsparsh** [comment]
@Rupa-Rd just make sure all descriptions are of same length and not more than 3 lines.

**Comment by swapnilsparsh** [comment]
@Rupa-Rd Thank you for contributing to this repo. Looking forward for more 🚀

**Pull request merged**
