### PR TITLE
Added functionality of copying the hashcode to clipboard on clicking the box (03-Random Color Generator)

### PR DESCRIPTION
**Pull request by zaidm124**
closes:https://github.com/swapnilsparsh/30DaysOfJavaScript/issues/35

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Please make it responsive, you can try using Grid/Flex

**Comment by zaidm124** [comment]
i have made the change

**Comment by swapnilsparsh** [comment]
@zaidm124 Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Review by swapnilsparsh — COMMENTED** [review]
Issue Resolved

**Pull request merged**
