### PR TITLE
Branch shivam

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
From my point of view this landing WebPage should be simple and a little bit designed , so i have removed some old designs and added my own designs  , colors and all .  This Webpage should have a simple and clean landing page.

@swapnilsparsh

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh  Please review it sir as i have made the webpage clean and tidy and a little bit  designed

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-03 12-44-56
Screenshot from 2023-02-03 12-45-02
Screenshot from 2023-02-03 12-45-07
Screenshot from 2023-02-03 12-45-11
Screenshot from 2023-02-03 12-45-16
Screenshot from 2023-02-03 12-45-19
Screenshot from 2023-02-03 12-45-24
Screenshot from 2023-02-03 12-45-35

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh I have uploaded the changes made by me in webpage. I Customised the landing page

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh  What are the next steps sir ? LIke i am beginner in Open source. SO what are the next steps

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 Appreciate your effforts but there is nothing seems to be changed as you have just changed the colors and some sizes.
You have to make a new UI.

**Comment by Bharadwajshivam28** [comment]
ok  will work on it @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Sir as this webpage is fully loaded with contents there is very less way to create a new landing page as there is very less way and that too is looking ugly

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh So can you give me some ideas about creating landing page of this much fully loaded content webpage

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 https://javascript30.com/ Go below where all projects are mentioned, try to make something like that 4 projects in 1 row and effect on hover with some good background and color combination.

**Comment by Bharadwajshivam28** [comment]
ok @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
it will be completed sir @swapnilsparsh

**Pull request closed without merging**
