### PR TITLE
Reset button added to make counter 0, save button to save the number. (08-Number Counter)

### PR DESCRIPTION
**Pull request by zaidm124**
closes:https://github.com/swapnilsparsh/30DaysOfJavaScript/issues/22

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Annotation 2021-10-02 231815
**Fix this on responsive.**

**Comment by zaidm124** [comment]
i have made the change, i hope it is fine now

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Annotation 2021-10-03 134722
**You can try to use flex.**

**Comment by zaidm124** [comment]
I am not really good in css, so if you could accept this pull request and assign the responsive issue to someone else it would be great

**Comment by swapnilsparsh** [comment]
> I am not really good in css, so if you could accept this pull request and assign the responsive issue to someone else it would be great

Sure.

**Comment by swapnilsparsh** [comment]
@zaidm124  Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Pull request merged**
