### PR TITLE
Added a New Project: 3D Distance Calculator 

### LINKED ISSUE #1600: Add a New Project: 3D Distance Calculator
### **Project Overview:**

I am looking to add a new project to the "30 Days of Code" website. This project will be a 3D Distance Calculator that allows users to compute the distance between two points in a three-dimensional space. The calculator should take the coordinates of two points as input and output the distance between them.

**Project Requirements:**

Input: The calculator should accept two sets of coordinates as input, each consisting of three values (x, y, z).
Output: The output should be the calculated distance between the two points.
Formula: Use the Euclidean distance formula:

image

**User Interface:**
A clean and simple UI for users to input coordinates.
A "Calculate" button to trigger the distance computation.
Display the result in a user-friendly manner.

Responsive Web Design Basics

> Let's enhance the learning experience on "30 Days of Code" with this exciting new project! If you have any questions or need further clarification, feel free to ask. Happy coding!

### Assignment Request:
**Please assign this task to me under GSSoC'24.**

Labels: `GSSoC` `Level3`

### PR DESCRIPTION
**Pull request by MrPC7**
### 🛠️ Fixes Issue 
Closes #1600 

### 👨‍💻 Changes proposed and Brief Description

1. New Project Added:

    - A new project has been created and included in the repository.

2. Update to the Projects List:

    - The newly added project has been included in the main list of projects within the repository.

3. Update to README.md:

    - The README.md file has been updated to include the new project, providing a brief overview and any necessary details.
    - Ensured that the project description highlights its key features and functionalities.

4. Responsive Design:

    - The new project is designed to be fully responsive, ensuring compatibility across various devices (desktops, tablets, and smartphones).

### ✅ Check List (Check all the applicable boxes) 

- ✅ My code doesn't break any part of the project
- ✅This PR does not contain plagiarized content.
- ✅ My Addition/Changes works properly and matches the overall repo pattern.
- ✅ The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

image

### CODE REVIEW

**Review by MrPC7 — COMMENTED** [review]
I have also reviewed my changes. I think everything is good.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Please fix the conflicts

**Comment by swapnilsparsh** [comment]
@MrPC7 Your project is missing from index.html, add it there also

**Review by MrPC7 — COMMENTED** [review]
added 3D distance calculator to the both files "index.html" and "indexold.html"

**Comment by swapnilsparsh** [comment]
@MrPC7 Thank you for contributing to this repo. Looking forward for more 🚀

**Pull request merged**
