### PR TITLE
58 - Simon game

### PR DESCRIPTION
**Pull request by Shrey3009**
Hi, I'm Shreyas and I have added simon game js project under GSSOC'22

Kindly review my PR and inform me if any changes are needed

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great Project
Resolve the conflicts also.
Update the project number as project number 55 has already been added to the repo.

**Comment by Shrey3009** [comment]
@swapnilsparsh I have changed the number to **56** as the projects added to the repo are **55** as of now. So should I keep it the same as the number was **53** when I started working on it today.

**Comment by Shrey3009** [comment]
@swapnilsparsh I have updated the project number to 58 as I saw up to 57 in the PRs

**Comment by swapnilsparsh** [comment]
@Shrey3009 Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Comment by Shrey3009** [comment]
@swapnilsparsh thanks for merging my PR, really boosted my confidence to contribute further

**Pull request merged**
