### PR TITLE
Added New Year countdown created with HTML CSS and JavaScript

### PR DESCRIPTION
**Pull request by AmolShelke2**
Hey Project Admin as you assign me this issue to work on I have completed the project and opened the pr regarding that to add my project in the 30daysofJavaScript repository and as you said to create an algorithm that will reset the timer once the year changed I have also added that here in the project so please go though it and I hope that you will merge my pull request thank you for your kindness

### CODE REVIEW

**Comment by AmolShelke2** [comment]
@swapnilsparsh please review this pull request

**Comment by swapnilsparsh** [comment]
@AmolShelke2 Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Comment by AmolShelke2** [comment]
Hey swapnil please add a level label and Gssoc label on my PR otherwise my
points will not be counted 🥲

**Comment by AmolShelke2** [comment]
Thanks for the kindness man ☺️

**Pull request merged**
