### PR TITLE
update-ui

### PR DESCRIPTION
**Pull request by vinitsingh-13**
issue #1037 
i had update the whole ui of the calculator

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Make it responsive for Mobile.

**Comment by vinitsingh-13** [comment]
> Make it responsive for Mobile.

issue done website is now fully responsive

**Comment by vinitsingh-13** [comment]
> Make it responsive for Mobile.

I have done it fully responsive so I am making a pull request

**Comment by vinitsingh-13** [comment]
i am making a new pull request

**Comment by vinitsingh-13** [comment]
> Make it responsive for Mobile.

i have done the work plz merge it

**Comment by vinitsingh-13** [comment]
i am making a new pull request for the ui

**Pull request closed without merging**
