### PR TITLE
Added save button and loader.

### PR DESCRIPTION
**Pull request by ananyakushal**
Added Save button which will be visible after clicking on Get Anime. Also added loader to whole card when data is getting fetched up and showing up on the webpage.

### ✅ Check List (Check all the applicable boxes) 

- [ ] My code doesn't break any part of the project
- [ ] This PR does not contain plagiarized content.
- [ ] My Addition/Changes works properly and matches the overall repo pattern.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@ananyakushal

1. Add a loader when data is being fetched then only show the data
2. When clicking on Save button it should open the pop up to save the file on your computer, right now you are opening the image in the new tab.

**Comment by ananyakushal** [comment]
@swapnilsparsh I have resolved the above issue. Please have a look on it.

**Comment by swapnilsparsh** [comment]
@ananyakushal everything is working fine just one small bug is there which is the loader gets finished before the image has been downloaded fully. As sometimes the loader is completed but the image loads up late.

**Comment by ananyakushal** [comment]
@swapnilsparsh is it ok now?

**Comment by ananyakushal** [comment]
Actually, the competition is about to end in few minutes. It would be so kind of you if you merge it before 11:59p.m.😊

**Comment by ananyakushal** [comment]
The scores have not been updated. Can you please look after it?

**Comment by swapnilsparsh** [comment]
> The scores have not been updated. Can you please look after it?

I merged your PR before 11:59, check it once more if the score are not updated then let me knoe

**Pull request merged**
