### PR TITLE
Done

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
@swapnilsparsh  I have created pagination without creating extra index files

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 Check your changes [here](https://deploy-preview-1009--30daysofjs.netlify.app/)

Why there is showing index4.html ?
Test

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 Check your changes [here](https://deploy-preview-1009--30daysofjs.netlify.app/)
> 
> Why there is showing index4.html ?
> Test
> 

There is no index and for one - two there is that also in folder

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 Check your changes [here](https://deploy-preview-1009--30daysofjs.netlify.app/)
> 
> Why there is showing index4.html ?
> Test
> 

I tried by removing index completely but for the links I need good webpage link so that is costly and all.. pasting the link simple after running doesn't work sometime

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 Check your changes [here](https://deploy-preview-1009--30daysofjs.netlify.app/)
> 
> Why there is showing index4.html ?
> Test
> 

So I have stored these in folders..like PROJECTS and index file

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 Check your changes [here](https://deploy-preview-1009--30daysofjs.netlify.app/)
> 
> Why there is showing index4.html ? Test

can it be like named as page1,page2 and like because working with links is getting messed . It doesnt have a proper link so sometimes it doesnt work

**Comment by Bharadwajshivam28** [comment]
so i have put these in folders

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 You dont have to make new folders or new files.
Make changes in index.html only and there is folder 30DaysOfJavaScript where there are 2 files script.js and style.css
Only in these files you have to make changes.

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by Bharadwajshivam28** [comment]
sir can i host website by netfily and then insert the link

**Comment by Bharadwajshivam28** [comment]
hositng the remaing pages like2,3,4,5,6 and 7

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 
Check [here](https://devempire.netlify.app/ambassador)
When you change the page then the url does not change only the card gets updated.

**Comment by Bharadwajshivam28** [comment]
because without creating files we need a proper link so i can host it using netfily and apply the link

**Comment by Bharadwajshivam28** [comment]
ok sir i will now do it

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Sir can i host the remaing pages by netfily

**Comment by Bharadwajshivam28** [comment]
Like i can get the link of page 2,3,4,5,6 and other

**Comment by swapnilsparsh** [comment]
You don't have to host the pages.
It will be automatically hosted when you commit changes

**Comment by Bharadwajshivam28** [comment]
sir like i am asking that without creating files

**Comment by Bharadwajshivam28** [comment]
when i give the links then sometime it run and soemtime it doesnt

**Comment by Bharadwajshivam28** [comment]
and when i am creating folders or file then doing then it is done ccorrectly

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh so please suggest me like how because creating folder or file then you dont want it sir so please sugeest

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh so please suggest me like how because creating folder or file then you dont want it sir so please sugeest

Told you here 
https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/1009#issuecomment-1445915261

**Comment by Bharadwajshivam28** [comment]
sir i understood that but without creating files or folders

**Comment by swapnilsparsh** [comment]
> like i am not able to understand that without creating seprate files how it will be done

You have to refresh the Div Tag inside which all the cards are there.

**Comment by Bharadwajshivam28** [comment]
Basically i have idea like we can create folders and each folder will have its 30 project and that will be clean and simple stuff

**Comment by Bharadwajshivam28** [comment]
> > like i am not able to understand that without creating seprate files how it will be done
> 
> You have to refresh the Div Tag inside which all the cards are there.

elaborate it sir some more

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Sir i not have much depth knowledge of these stuff

**Comment by Bharadwajshivam28** [comment]
SO can i do it by creating seprate folders

**Comment by Bharadwajshivam28** [comment]
I have spent whole night sir yesterday so please let me do it

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 Appreciate your efforts but this is not the correct way to do so.

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by Bharadwajshivam28** [comment]
sir please reach my one blog issue

**Pull request closed without merging**
