### PR TITLE
Updated / Removed erroors in file

### PR DESCRIPTION
**Pull request by satyammishra0**
### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@satyammishra0 What you have fixed ?

**Comment by satyammishra0** [comment]
Your previous file have some unnecessary : colons  which were ruining the file

**Comment by satyammishra0** [comment]
have you merged ?

**Comment by swapnilsparsh** [comment]
Unnecessary changes.

**Pull request closed without merging**
