### PR TITLE
Added my project weeblist

### PR DESCRIPTION
**Pull request by bartick**
Added a small js project that requires the use of fetch feature and looping of elements . A project that weebs like me might like. This project can be used to easily search and visualise all the available anime/manga in MAL. 
I did this under GSSoC'22. If I did any mistake hoping you will rectify me.

### CODE REVIEW

**Comment by bartick** [comment]
O also sorry I mistakenly added a space in the folder name. The correct preview from that netlify bot will be https://deploy-preview-172--30daysofjs.netlify.app/50%20-%20weeblist/

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great project
Update screenshot of the project in assets folder and update the number of your project as project number 50 is already there on the repo

**Comment by bartick** [comment]
Thanks for telling me. I changed the number from 50 to 53.
Hope I did everything correctly

**Comment by bartick** [comment]
Also fixed the issue #147 on the last commit
Hope you can forgive me for not opening a new PR.

**Pull request closed without merging**
