### PR TITLE
improved pagination buttons

### LINKED ISSUE #1071: Title: Improve pagination buttons styling and improve the footer section
### Which pre-existing JavaScript project will you be working on?

-

### Describe your enhancement/improvement

Hey @swapnilsparsh I would like to improve this section 
image

Kindly assign me this issue and I can solve it quickly

### Anything you need to say to the Reviewers

_No response_

### Add any other context or relevant screenshots about the enhancement here.

_No response_

### PR DESCRIPTION
**Pull request by ratishjain12**
### 🛠️ Fixes Issue (Number)
@swapnilsparsh 
Fixes #1071 
Screenshot 2023-10-08 104038

image

I have enhanced pagination section kindly merge it :)

### ✅ Check List (Check all the applicable boxes) 

- [x] My code doesn't break any part of the project
- [x] This PR does not contain plagiarized content.
- [x] My Addition/Changes works properly and matches the overall repo pattern.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
1. Resolve the conflicts.
2. Make the active page number with some other background color to make it differ from others

**Comment by ratishjain12** [comment]
> 1. Resolve the conflicts.
> 2. Make the active page number with some other background color to make it differ from others

Sure just a sec will ping you when its done

**Comment by swapnilsparsh** [comment]
@ratishjain12 you can check the conflicts above as I can merge your code unless conflicts are resolved.

**Comment by ratishjain12** [comment]
@swapnilsparsh I think now there is no conflicts and I have added focus color on buttons :)

**Comment by swapnilsparsh** [comment]
@ratishjain12 When you open the website for the first time then by default page number 1 should be highlighted as page number 1 is opened.

**Comment by ratishjain12** [comment]
Ok let me check

**Comment by ratishjain12** [comment]
@swapnilsparsh now it done :)

**Comment by swapnilsparsh** [comment]
@ratishjain12 Clicking on Previous or Next button then highlight is not working. Also If you click anywhere on the page then also highlight of the button gets removed.

**Comment by ratishjain12** [comment]
> @ratishjain12 Clicking on Previous or Next button then highlight is not working. Also If you click anywhere on the page then also highlight of the button gets removed.

Ok I'll look into it

**Comment by ratishjain12** [comment]
@swapnilsparsh I have finished all the things required page 1 by default is active on clicking next and prev the state is maintained as well as clicking anywhere else the focus is not getting removed.

Kindly merge thank you :)

**Comment by ratishjain12** [comment]
> @ratishjain12 Thank You for your contribution! Excited for more in the future! 🥂

Mention not will do 😁

**Pull request merged**
