### PR TITLE
TailwindCSS - add development and production HOW-TO section

### PR DESCRIPTION
**Pull request by alexventuraio**
- Add some config and instruction on how to use [TailwindCSS](https://tailwindcss.com/docs/installation) in development and production.
- Push the minified version of the `assets/tailwind.css` file, ready for production.

### CODE REVIEW

**Comment by alexventuraio** [comment]
> > > @alexventuraio Thank you for your contribution. Looking forward to more such amazing contributions 🥂
> > 
> > 
> > My pleasure! I'll keep an eye on the pending stuff! 😎
> 
> Can you see the repo language, its stating 98% HTML, can you fix it as it is not a HTML project.


Well, the thing is that this is not something we can configure, basically, Github analyzes the repo files and its contenten and builds the statistics based on that!
And we seem to have much more HTML code versus the JS code present in the repo.

**Comment by swapnilsparsh** [comment]
> > > > @alexventuraio Thank you for your contribution. Looking forward to more such amazing contributions 🥂
> > > 
> > > 
> > > My pleasure! I'll keep an eye on the pending stuff! 😎
> > 
> > 
> > Can you see the repo language, its stating 98% HTML, can you fix it as it is not a HTML project.
> 
> Well, the thing is that this is not something we can configure, basically, Github analyzes the repo files and its contenten and builds the statistics based on that! And we seem to have much more HTML code versus the JS code present in the repo.

But CSS is 0% 😂
After merging your Tailwind CSS PR there is this issue that's why I was trying you to fix it.

**Comment by alexventuraio** [comment]
Oh, I see!
Maybe that is because TailwindCSS is more verbose in the sense that it uses lots of classes in the HTML markup. For example, borders and colors and sizing has is own class name for example:

```HTML
  <img class="w-32 h-32 md:w-48 md:h-auto md:rounded-none rounded-full mx-auto" src="/sarah-dayan.jpg" alt="" width="384" height="512">
```

In normal CSS, we could use only one class to give the `img` tag the same styles:
```html
  <img class="my-image" src="/sarah-dayan.jpg">

# CSS:
my-image {
  width: 32px;
  height: 32px;
  border-radious: ;
 marging: auto;
}
```

And the amount of HTML code is reduced and the CSS is incremented.
That's the sense of Tailwind, to deliver more isolated utility classes instead of offering components as Bootstrap does. This will offer users more control and freedom when it comes to building UIs but the downside is that you are repeating classes in the HTML markup more often.

What do you think?
Should we think of a rollback on TailwindCSS stuff? 🤔

**Comment by swapnilsparsh** [comment]
> Oh, I see! Maybe that is because TailwindCSS is more verbose in the sense that it uses lots of classes in the HTML markup. For example, borders and colors and sizing has is own class name:
> 
> ```
> 
> ```
> 
> In normal CSS, we could use only one class to give the `img` tag the same styles:
> 
> ```
> 
> 
> # CSS:
> my-image {
>   width: 32px;
>   height: 32px;
>   border-radious: ;
>   margin: auto;
> }
> ```
> 
> And the amount of HTML code is reduced and the CSS is incremented. This way, there will be lots of repetitive CSS statements like `margin: auto` in the CSS files because we are maybe giving the same `margin` value to different elements.
> 
> The sense of Tailwind is to deliver more isolated utility classes instead of offering components as Bootstrap does. This will offer users more control and freedom when it comes to building UIs but the downside is that you are repeating classes in the HTML markup, not in CSS.
> 
> What do you think? Should we think of a rollback on TailwindCSS stuff? 🤔

Ohk got the issue.
In repo it's showing 0% CSS so it's not a good impression on others.
If possible try to fix this in Tailwind CSS only as it is not a good option for rolling back to normal CSS.
I am assigning you the issue then please look after it. #69

**Pull request merged**
