### PR TITLE
112 - World Clock added

### LINKED ISSUE #1201: Title:  Making clock to World Clock
### Is your feature request related to a problem? Please describe.

If we have a clock then why we just see time of our country and not other.

### Describe the solution you'd like.

i want to transform existing clock to world clock so we can see time of any country by just selecting that country. Just select any country and you will be able to see the time, i will also add digital clock

### Describe alternatives you've considered.

There might not have any other feature than this.

### Add any other context or screenshots about the feature request here.

Screenshot from 2024-05-11 09-21-02

### PR DESCRIPTION
**Pull request by VaibhavDhanani**
### 👨‍💻 Changes proposed and Brief Description

I have added simple world clock that shows most of country's time.

### ✅ Check List (Check all the applicable boxes) 

- [ ] My code doesn't break any part of the project
- [ ] This PR does not contain plagiarized content.
- [✅] My Addition/Changes works properly and matches the overall repo pattern.
- [✅] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

Not any.

### 📷 Screenshot
Screenshot from 2024-05-12 19-46-46
Screenshot from 2024-05-12 19-47-03

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@VaibhavDhanani I can not see your files change. Try to make a new commit with new folder

**Comment by swapnilsparsh** [comment]
@VaibhavDhanani Any update #1201

**Comment by VaibhavDhanani** [comment]
> #1201

i don't know how to deploy on netlify/30daysodjs. if you can guide me , it will be good for me.

**Comment by swapnilsparsh** [comment]
> > #1201
> 
> i don't know how to deploy on netlify/30daysodjs. if you can guide me , it will be good for me.

You dont have to deploy, just push your code because I can't see your code
image

**Pull request closed without merging**
