### PR TITLE
Added a new JavaScript Project Quiz app

### PR DESCRIPTION
**Pull request by tm2582001**
Added a new JavaScript project quiz app.

I'm adding this project as a part of GSSOC'22 contribution.

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great Project
Update the project number as project number 50 has already been added to the repo.
Add the screenshot of your project also in the assets folder.

**Comment by tm2582001** [comment]
@swapnilsparsh I have made changes that were requested by you.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great Project
Update the project number as project number 55 has already been added to the repo.

**Comment by tm2582001** [comment]
@swapnilsparsh I have updated project number

**Comment by swapnilsparsh** [comment]
@tm2582001 Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Pull request merged**
