### PR TITLE
Adding Guess The Shape Game 

### PR DESCRIPTION
**Pull request by codewithganeshhh**
### 👨‍💻 Changes proposed and Brief Description:
- This project is built on a basic web tech stacks such as HTML, CSS and JavaScript.
- This is a single-player game.
- - The player will tell the shape formed using dots.
- Options are given in the game.
- If player reaches to 10 points will win the game.
- If player looses all the 5 lives will lose the game.

### ✅ Check List (Check all the applicable boxes) 

- [✅ ] My code doesn't break any part of the project
- [ ✅] This PR does not contain plagiarized content.
- [ ✅] My Addition/Changes works properly and matches the overall repo pattern.
- [✅ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Add your project in index.html file also

**Comment by codewithganeshhh** [comment]
Autopull ? what can I do

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Make it responsive for mobile screens also
image


When game is over there should be an option to play again.

**Comment by swapnilsparsh** [comment]
@codewithganeshhh Any update ?

**Comment by codewithganeshhh** [comment]
why Auto Label Fail ?

**Comment by codewithganeshhh** [comment]
how to solve ? @swapnilsparsh

**Pull request closed without merging**
