### PR TITLE
Added a Side Navbar

### PR DESCRIPTION
**Pull request by KiranAminPanjwani**
On Dark Mode:
image
image

On Light Mode:
image
image

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great work, but when the sidebar is opening it is hiding the contents that it should not, so try to fix it.

**Comment by KiranAminPanjwani** [comment]
@swapnilsparsh Actually I have designed an overlay sidebar. But no worries I will fix this.

**Comment by KiranAminPanjwani** [comment]
@swapnilsparsh I have updated the Side Navbar, kindly check it.

Without Toggle:
image

On Toggle:
image

**Comment by swapnilsparsh** [comment]
@KiranAminPanjwani Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Comment by KiranAminPanjwani** [comment]
> @KiranAminPanjwani Thank you for your contribution. Looking forward to more such amazing contributions 🥂

Thank you so much!!! ❤️

**Pull request merged**
