### PR TITLE
Project: Captcha Generator Added

### LINKED ISSUE #215: Add a Captcha Generator App
##### This project would be under GSSoC'22.

### PR DESCRIPTION
**Pull request by Atharv-110**
### Fixes #215 
@swapnilsparsh, Please do Review my PR.

### CODE REVIEW

**Comment by Atharv-110** [comment]
### @swapnilsparsh can you please tell me why this auto label check is failing, I've just resolved the conflict that's it.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Update the project number as 66 is already there.

**Comment by Atharv-110** [comment]
Which no. Should i update?

**Comment by swapnilsparsh** [comment]
> Which no. Should i update?

80

**Pull request closed without merging**
