### PR TITLE
Added Bubble Game

### PR DESCRIPTION
**Pull request by kkhushie**
image

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Add your project to index.html with proper screenshot

**Comment by kkhushie** [comment]
@swapnilsparsh  Added my project Bubble Game to index.html with proper screenshot.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Everything is working fine just remove the sound files and from the code also.

**Comment by kkhushie** [comment]
Removed the sound files and from the code also. ✅

**Comment by kkhushie** [comment]
updated script.js

**Pull request closed without merging**
